### ISSUE TITLE
Require __init__.py in sub-packages

### ISSUE THREAD

**Issue by Hoshock** [deshima-dev/decode#19]
Some sub-packages do not have `__init__.py` in their directories. Due to the lack of `__init__.py` in `decode.core.array`, `decode.core.cube`, `decode.utils.misc`, and `decode.utils.ndarray`, *sphinx* does not output their documentation.

**Comment by astropenguin** [comment]
@Hoshock Thank you for finding this! Could you fix it if you have time to do so?

**Comment by Hoshock** [comment]
Sure! I'll deal with it.
