### ISSUE TITLE
Fix 2D Gaussian fitting and related title formatting of qlook

### ISSUE THREAD

**Issue by ShinjiFujita** [deshima-dev/decode#197]
- When the fit fails, the image does not come out.
- The number of digits displayed in Peak is not enough.
- Sigma sometimes becomes negative.
- The absolute value of theta exceeds 360.

**Comment by astropenguin** [comment]
@ShinjiFujita san, thank you for this issue! Just a tiny thing, could you also remove unnecessary closing parentheses from L274 and L519?

```diff
- f"dEl = {popt[2]:+.2f} [{cont.lat.attrs['units']}]),\n"
+ f"dEl = {popt[2]:+.2f} [{cont.lat.attrs['units']}],\n"
```
